b = input('Digite algo: ')
print('O tariavelipo primitivo desse valor é :', type(b))
print('É somente espaços? ', b.isspace())
print('É um numero? ', b.isnumeric())
print('É alfabetico? ', b.isalpha())
print('É alfanumerico? ', b.isalnum())
print('Esta em maiusculas? ', b.isupper())
print('Esta em minuscula?', b.islower())
print('Esta capitalizada?', b.istitle())
